export const FETCH_STAR_WARS_REQUEST = 'FETCH_STAR_WARS_REQUEST';
export const FETCH_STAR_WARS_SUCCESS = 'FETCH_STAR_WARS_SUCCESS';
export const FETCH_STAR_WARS_PLANETS_REQUEST = 'FETCH_STAR_WARS_PLANETS_REQUEST';
export const FETCH_STAR_WARS_PLANETS_SUCCESS = 'FETCH_STAR_WARS_PLANETS_SUCCESS';
export const QUEUE_CHANNEL_REQUEST = 'QUEUE_CHANNEL_REQUEST';
export const CONFIRMATION = 'CONFIRMATION';